const API_ROOT_PATH = "/api/v1";
const DEV_ENVIRONMENT = "DEV";
const PROD_ENVIRONMENT = "PROD";
const INTERNAL_SERVER_ERROR_CODE = "INTERNAL_SERVER_ERROR";
const INTERNAL_SERVER_ERROR_MESSAGE = "Internal server error";

export default {
  API_ROOT_PATH,
  DEV_ENVIRONMENT,
  PROD_ENVIRONMENT,
  INTERNAL_SERVER_ERROR_CODE,
  INTERNAL_SERVER_ERROR_MESSAGE
};
